version: '3.8'
services:
  
  bingo:
    image: bingo:latest
    container_name: bingo
    ports:
      - '3002:3000'
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_URL=redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@redis:6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - backend
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  cache:
    driver: local